// Code generated by MockGen. DO NOT EDIT.
// Source: email.go
//
// Generated by this command:
//
//	mockgen -source=email.go -destination=mock/email_client_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEmailClient is a mock of EmailClient interface.
type MockEmailClient struct {
	ctrl     *gomock.Controller
	recorder *MockEmailClientMockRecorder
	isgomock struct{}
}

// MockEmailClientMockRecorder is the mock recorder for MockEmailClient.
type MockEmailClientMockRecorder struct {
	mock *MockEmailClient
}

// NewMockEmailClient creates a new mock instance.
func NewMockEmailClient(ctrl *gomock.Controller) *MockEmailClient {
	mock := &MockEmailClient{ctrl: ctrl}
	mock.recorder = &MockEmailClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailClient) EXPECT() *MockEmailClientMockRecorder {
	return m.recorder
}

// SendPasswordChangeNotification mocks base method.
func (m *MockEmailClient) SendPasswordChangeNotification(to string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendPasswordChangeNotification", to)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendPasswordChangeNotification indicates an expected call of SendPasswordChangeNotification.
func (mr *MockEmailClientMockRecorder) SendPasswordChangeNotification(to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPasswordChangeNotification", reflect.TypeOf((*MockEmailClient)(nil).SendPasswordChangeNotification), to)
}

// SendPasswordReset mocks base method.
func (m *MockEmailClient) SendPasswordReset(to, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendPasswordReset", to, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendPasswordReset indicates an expected call of SendPasswordReset.
func (mr *MockEmailClientMockRecorder) SendPasswordReset(to, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPasswordReset", reflect.TypeOf((*MockEmailClient)(nil).SendPasswordReset), to, token)
}
