// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/recipe_tag/add_tags_usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/recipe_tag/add_tags_usecase.go -destination=internal/usecase/mock/add_tags_usecase_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAddTagsUseCase is a mock of AddTagsUseCase interface.
type MockAddTagsUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockAddTagsUseCaseMockRecorder
	isgomock struct{}
}

// MockAddTagsUseCaseMockRecorder is the mock recorder for MockAddTagsUseCase.
type MockAddTagsUseCaseMockRecorder struct {
	mock *MockAddTagsUseCase
}

// NewMockAddTagsUseCase creates a new mock instance.
func NewMockAddTagsUseCase(ctrl *gomock.Controller) *MockAddTagsUseCase {
	mock := &MockAddTagsUseCase{ctrl: ctrl}
	mock.recorder = &MockAddTagsUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAddTagsUseCase) EXPECT() *MockAddTagsUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockAddTagsUseCase) Execute(ctx context.Context, recipeID, userID int64, tagIDs []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, recipeID, userID, tagIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockAddTagsUseCaseMockRecorder) Execute(ctx, recipeID, userID, tagIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockAddTagsUseCase)(nil).Execute), ctx, recipeID, userID, tagIDs)
}
