// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/recipe_image/add_image_usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/recipe_image/add_image_usecase.go -destination=internal/usecase/mock/add_image_usecase_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/seka/reci-pin/backend/internal/domain/model"
	gomock "go.uber.org/mock/gomock"
)

// MockAddImageUseCase is a mock of AddImageUseCase interface.
type MockAddImageUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockAddImageUseCaseMockRecorder
	isgomock struct{}
}

// MockAddImageUseCaseMockRecorder is the mock recorder for MockAddImageUseCase.
type MockAddImageUseCaseMockRecorder struct {
	mock *MockAddImageUseCase
}

// NewMockAddImageUseCase creates a new mock instance.
func NewMockAddImageUseCase(ctrl *gomock.Controller) *MockAddImageUseCase {
	mock := &MockAddImageUseCase{ctrl: ctrl}
	mock.recorder = &MockAddImageUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAddImageUseCase) EXPECT() *MockAddImageUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockAddImageUseCase) Execute(ctx context.Context, recipeID, userID int64, imagePath string) (*model.RecipeImage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, recipeID, userID, imagePath)
	ret0, _ := ret[0].(*model.RecipeImage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockAddImageUseCaseMockRecorder) Execute(ctx, recipeID, userID, imagePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockAddImageUseCase)(nil).Execute), ctx, recipeID, userID, imagePath)
}
