// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/auth/change_password_usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/auth/change_password_usecase.go -destination=internal/usecase/mock/change_password_usecase_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	auth "github.com/seka/reci-pin/backend/internal/usecase/auth"
	gomock "go.uber.org/mock/gomock"
)

// MockChangePasswordUseCase is a mock of ChangePasswordUseCase interface.
type MockChangePasswordUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockChangePasswordUseCaseMockRecorder
	isgomock struct{}
}

// MockChangePasswordUseCaseMockRecorder is the mock recorder for MockChangePasswordUseCase.
type MockChangePasswordUseCaseMockRecorder struct {
	mock *MockChangePasswordUseCase
}

// NewMockChangePasswordUseCase creates a new mock instance.
func NewMockChangePasswordUseCase(ctrl *gomock.Controller) *MockChangePasswordUseCase {
	mock := &MockChangePasswordUseCase{ctrl: ctrl}
	mock.recorder = &MockChangePasswordUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChangePasswordUseCase) EXPECT() *MockChangePasswordUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockChangePasswordUseCase) Execute(ctx context.Context, userID int64, input auth.ChangePasswordInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, userID, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockChangePasswordUseCaseMockRecorder) Execute(ctx, userID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockChangePasswordUseCase)(nil).Execute), ctx, userID, input)
}
