// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/tag/create_tag_usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/tag/create_tag_usecase.go -destination=internal/usecase/mock/create_tag_usecase_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/seka/reci-pin/backend/internal/domain/model"
	gomock "go.uber.org/mock/gomock"
)

// MockCreateTagUseCase is a mock of CreateTagUseCase interface.
type MockCreateTagUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockCreateTagUseCaseMockRecorder
	isgomock struct{}
}

// MockCreateTagUseCaseMockRecorder is the mock recorder for MockCreateTagUseCase.
type MockCreateTagUseCaseMockRecorder struct {
	mock *MockCreateTagUseCase
}

// NewMockCreateTagUseCase creates a new mock instance.
func NewMockCreateTagUseCase(ctrl *gomock.Controller) *MockCreateTagUseCase {
	mock := &MockCreateTagUseCase{ctrl: ctrl}
	mock.recorder = &MockCreateTagUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateTagUseCase) EXPECT() *MockCreateTagUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCreateTagUseCase) Execute(ctx context.Context, name string) (*model.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, name)
	ret0, _ := ret[0].(*model.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockCreateTagUseCaseMockRecorder) Execute(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCreateTagUseCase)(nil).Execute), ctx, name)
}
