// Code generated by MockGen. DO NOT EDIT.
// Source: create_recipe_image_usecase.go
//
// Generated by this command:
//
//	mockgen -source=create_recipe_image_usecase.go -destination=../mock/create_recipe_image_usecase_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/seka/reci-pin/backend/internal/domain/model"
	recipe_image "github.com/seka/reci-pin/backend/internal/usecase/recipe_image"
	gomock "go.uber.org/mock/gomock"
)

// MockCreateRecipeImageUseCase is a mock of CreateRecipeImageUseCase interface.
type MockCreateRecipeImageUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockCreateRecipeImageUseCaseMockRecorder
	isgomock struct{}
}

// MockCreateRecipeImageUseCaseMockRecorder is the mock recorder for MockCreateRecipeImageUseCase.
type MockCreateRecipeImageUseCaseMockRecorder struct {
	mock *MockCreateRecipeImageUseCase
}

// NewMockCreateRecipeImageUseCase creates a new mock instance.
func NewMockCreateRecipeImageUseCase(ctrl *gomock.Controller) *MockCreateRecipeImageUseCase {
	mock := &MockCreateRecipeImageUseCase{ctrl: ctrl}
	mock.recorder = &MockCreateRecipeImageUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateRecipeImageUseCase) EXPECT() *MockCreateRecipeImageUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCreateRecipeImageUseCase) Execute(ctx context.Context, input recipe_image.CreateRecipeImageInput) (*model.PublicRecipeImage, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(*model.PublicRecipeImage)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Execute indicates an expected call of Execute.
func (mr *MockCreateRecipeImageUseCaseMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCreateRecipeImageUseCase)(nil).Execute), ctx, input)
}
