// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/recipe/create_recipe_usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/recipe/create_recipe_usecase.go -destination=internal/usecase/mock/create_recipe_usecase_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/seka/reci-pin/backend/internal/domain/model"
	recipe "github.com/seka/reci-pin/backend/internal/usecase/recipe"
	gomock "go.uber.org/mock/gomock"
)

// MockCreateRecipeUseCase is a mock of CreateRecipeUseCase interface.
type MockCreateRecipeUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockCreateRecipeUseCaseMockRecorder
	isgomock struct{}
}

// MockCreateRecipeUseCaseMockRecorder is the mock recorder for MockCreateRecipeUseCase.
type MockCreateRecipeUseCaseMockRecorder struct {
	mock *MockCreateRecipeUseCase
}

// NewMockCreateRecipeUseCase creates a new mock instance.
func NewMockCreateRecipeUseCase(ctrl *gomock.Controller) *MockCreateRecipeUseCase {
	mock := &MockCreateRecipeUseCase{ctrl: ctrl}
	mock.recorder = &MockCreateRecipeUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateRecipeUseCase) EXPECT() *MockCreateRecipeUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCreateRecipeUseCase) Execute(ctx context.Context, input recipe.CreateRecipeInput) (*model.Recipe, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(*model.Recipe)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockCreateRecipeUseCaseMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCreateRecipeUseCase)(nil).Execute), ctx, input)
}
