// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/tag/delete_tag_usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/tag/delete_tag_usecase.go -destination=internal/usecase/mock/delete_tag_usecase_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDeleteTagUseCase is a mock of DeleteTagUseCase interface.
type MockDeleteTagUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteTagUseCaseMockRecorder
	isgomock struct{}
}

// MockDeleteTagUseCaseMockRecorder is the mock recorder for MockDeleteTagUseCase.
type MockDeleteTagUseCaseMockRecorder struct {
	mock *MockDeleteTagUseCase
}

// NewMockDeleteTagUseCase creates a new mock instance.
func NewMockDeleteTagUseCase(ctrl *gomock.Controller) *MockDeleteTagUseCase {
	mock := &MockDeleteTagUseCase{ctrl: ctrl}
	mock.recorder = &MockDeleteTagUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteTagUseCase) EXPECT() *MockDeleteTagUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockDeleteTagUseCase) Execute(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockDeleteTagUseCaseMockRecorder) Execute(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockDeleteTagUseCase)(nil).Execute), ctx, id)
}
