// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/recipe/delete_recipe_usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/recipe/delete_recipe_usecase.go -destination=internal/usecase/mock/delete_recipe_usecase_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDeleteRecipeUseCase is a mock of DeleteRecipeUseCase interface.
type MockDeleteRecipeUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteRecipeUseCaseMockRecorder
	isgomock struct{}
}

// MockDeleteRecipeUseCaseMockRecorder is the mock recorder for MockDeleteRecipeUseCase.
type MockDeleteRecipeUseCaseMockRecorder struct {
	mock *MockDeleteRecipeUseCase
}

// NewMockDeleteRecipeUseCase creates a new mock instance.
func NewMockDeleteRecipeUseCase(ctrl *gomock.Controller) *MockDeleteRecipeUseCase {
	mock := &MockDeleteRecipeUseCase{ctrl: ctrl}
	mock.recorder = &MockDeleteRecipeUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteRecipeUseCase) EXPECT() *MockDeleteRecipeUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockDeleteRecipeUseCase) Execute(ctx context.Context, id, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockDeleteRecipeUseCaseMockRecorder) Execute(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockDeleteRecipeUseCase)(nil).Execute), ctx, id, userID)
}
