// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/auth/get_user_usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/auth/get_user_usecase.go -destination=internal/usecase/mock/get_user_usecase_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/seka/reci-pin/backend/internal/domain/model"
	gomock "go.uber.org/mock/gomock"
)

// MockGetUserUseCase is a mock of GetUserUseCase interface.
type MockGetUserUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetUserUseCaseMockRecorder
	isgomock struct{}
}

// MockGetUserUseCaseMockRecorder is the mock recorder for MockGetUserUseCase.
type MockGetUserUseCaseMockRecorder struct {
	mock *MockGetUserUseCase
}

// NewMockGetUserUseCase creates a new mock instance.
func NewMockGetUserUseCase(ctrl *gomock.Controller) *MockGetUserUseCase {
	mock := &MockGetUserUseCase{ctrl: ctrl}
	mock.recorder = &MockGetUserUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetUserUseCase) EXPECT() *MockGetUserUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetUserUseCase) Execute(ctx context.Context, userID int64) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, userID)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetUserUseCaseMockRecorder) Execute(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetUserUseCase)(nil).Execute), ctx, userID)
}
