// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/recipe/get_recipe_usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/recipe/get_recipe_usecase.go -destination=internal/usecase/mock/get_recipe_usecase_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/seka/reci-pin/backend/internal/domain/model"
	gomock "go.uber.org/mock/gomock"
)

// MockGetRecipeUseCase is a mock of GetRecipeUseCase interface.
type MockGetRecipeUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetRecipeUseCaseMockRecorder
	isgomock struct{}
}

// MockGetRecipeUseCaseMockRecorder is the mock recorder for MockGetRecipeUseCase.
type MockGetRecipeUseCaseMockRecorder struct {
	mock *MockGetRecipeUseCase
}

// NewMockGetRecipeUseCase creates a new mock instance.
func NewMockGetRecipeUseCase(ctrl *gomock.Controller) *MockGetRecipeUseCase {
	mock := &MockGetRecipeUseCase{ctrl: ctrl}
	mock.recorder = &MockGetRecipeUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetRecipeUseCase) EXPECT() *MockGetRecipeUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetRecipeUseCase) Execute(ctx context.Context, id, userID int64) (*model.Recipe, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, id, userID)
	ret0, _ := ret[0].(*model.Recipe)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetRecipeUseCaseMockRecorder) Execute(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetRecipeUseCase)(nil).Execute), ctx, id, userID)
}
