// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/tag/get_all_tags_usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/tag/get_all_tags_usecase.go -destination=internal/usecase/mock/get_all_tags_usecase_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/seka/reci-pin/backend/internal/domain/model"
	gomock "go.uber.org/mock/gomock"
)

// MockGetAllTagsUseCase is a mock of GetAllTagsUseCase interface.
type MockGetAllTagsUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetAllTagsUseCaseMockRecorder
	isgomock struct{}
}

// MockGetAllTagsUseCaseMockRecorder is the mock recorder for MockGetAllTagsUseCase.
type MockGetAllTagsUseCaseMockRecorder struct {
	mock *MockGetAllTagsUseCase
}

// NewMockGetAllTagsUseCase creates a new mock instance.
func NewMockGetAllTagsUseCase(ctrl *gomock.Controller) *MockGetAllTagsUseCase {
	mock := &MockGetAllTagsUseCase{ctrl: ctrl}
	mock.recorder = &MockGetAllTagsUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetAllTagsUseCase) EXPECT() *MockGetAllTagsUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetAllTagsUseCase) Execute(ctx context.Context) ([]model.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx)
	ret0, _ := ret[0].([]model.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetAllTagsUseCaseMockRecorder) Execute(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetAllTagsUseCase)(nil).Execute), ctx)
}
