// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/recipe/get_user_recipes_usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/recipe/get_user_recipes_usecase.go -destination=internal/usecase/mock/get_user_recipes_usecase_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/seka/reci-pin/backend/internal/domain/model"
	gomock "go.uber.org/mock/gomock"
)

// MockGetUserRecipesUseCase is a mock of GetUserRecipesUseCase interface.
type MockGetUserRecipesUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetUserRecipesUseCaseMockRecorder
	isgomock struct{}
}

// MockGetUserRecipesUseCaseMockRecorder is the mock recorder for MockGetUserRecipesUseCase.
type MockGetUserRecipesUseCaseMockRecorder struct {
	mock *MockGetUserRecipesUseCase
}

// NewMockGetUserRecipesUseCase creates a new mock instance.
func NewMockGetUserRecipesUseCase(ctrl *gomock.Controller) *MockGetUserRecipesUseCase {
	mock := &MockGetUserRecipesUseCase{ctrl: ctrl}
	mock.recorder = &MockGetUserRecipesUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetUserRecipesUseCase) EXPECT() *MockGetUserRecipesUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetUserRecipesUseCase) Execute(ctx context.Context, userID int64) ([]model.Recipe, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, userID)
	ret0, _ := ret[0].([]model.Recipe)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetUserRecipesUseCaseMockRecorder) Execute(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetUserRecipesUseCase)(nil).Execute), ctx, userID)
}
