// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/recipe_tag/remove_tags_usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/recipe_tag/remove_tags_usecase.go -destination=internal/usecase/mock/remove_tags_usecase_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRemoveTagsUseCase is a mock of RemoveTagsUseCase interface.
type MockRemoveTagsUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockRemoveTagsUseCaseMockRecorder
	isgomock struct{}
}

// MockRemoveTagsUseCaseMockRecorder is the mock recorder for MockRemoveTagsUseCase.
type MockRemoveTagsUseCaseMockRecorder struct {
	mock *MockRemoveTagsUseCase
}

// NewMockRemoveTagsUseCase creates a new mock instance.
func NewMockRemoveTagsUseCase(ctrl *gomock.Controller) *MockRemoveTagsUseCase {
	mock := &MockRemoveTagsUseCase{ctrl: ctrl}
	mock.recorder = &MockRemoveTagsUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRemoveTagsUseCase) EXPECT() *MockRemoveTagsUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockRemoveTagsUseCase) Execute(ctx context.Context, recipeID, userID int64, tagIDs []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, recipeID, userID, tagIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockRemoveTagsUseCaseMockRecorder) Execute(ctx, recipeID, userID, tagIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockRemoveTagsUseCase)(nil).Execute), ctx, recipeID, userID, tagIDs)
}
