// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/auth/request_password_reset_usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/auth/request_password_reset_usecase.go -destination=internal/usecase/mock/request_password_reset_usecase_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRequestPasswordResetUseCase is a mock of RequestPasswordResetUseCase interface.
type MockRequestPasswordResetUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockRequestPasswordResetUseCaseMockRecorder
	isgomock struct{}
}

// MockRequestPasswordResetUseCaseMockRecorder is the mock recorder for MockRequestPasswordResetUseCase.
type MockRequestPasswordResetUseCaseMockRecorder struct {
	mock *MockRequestPasswordResetUseCase
}

// NewMockRequestPasswordResetUseCase creates a new mock instance.
func NewMockRequestPasswordResetUseCase(ctrl *gomock.Controller) *MockRequestPasswordResetUseCase {
	mock := &MockRequestPasswordResetUseCase{ctrl: ctrl}
	mock.recorder = &MockRequestPasswordResetUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRequestPasswordResetUseCase) EXPECT() *MockRequestPasswordResetUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockRequestPasswordResetUseCase) Execute(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockRequestPasswordResetUseCaseMockRecorder) Execute(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockRequestPasswordResetUseCase)(nil).Execute), ctx, email)
}
