// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/auth/reset_password_usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/auth/reset_password_usecase.go -destination=internal/usecase/mock/reset_password_usecase_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	auth "github.com/seka/reci-pin/backend/internal/usecase/auth"
	gomock "go.uber.org/mock/gomock"
)

// MockResetPasswordUseCase is a mock of ResetPasswordUseCase interface.
type MockResetPasswordUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockResetPasswordUseCaseMockRecorder
	isgomock struct{}
}

// MockResetPasswordUseCaseMockRecorder is the mock recorder for MockResetPasswordUseCase.
type MockResetPasswordUseCaseMockRecorder struct {
	mock *MockResetPasswordUseCase
}

// NewMockResetPasswordUseCase creates a new mock instance.
func NewMockResetPasswordUseCase(ctrl *gomock.Controller) *MockResetPasswordUseCase {
	mock := &MockResetPasswordUseCase{ctrl: ctrl}
	mock.recorder = &MockResetPasswordUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResetPasswordUseCase) EXPECT() *MockResetPasswordUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockResetPasswordUseCase) Execute(ctx context.Context, input auth.ResetPasswordInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockResetPasswordUseCaseMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockResetPasswordUseCase)(nil).Execute), ctx, input)
}
