// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/recipe/search_recipes_usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/recipe/search_recipes_usecase.go -destination=internal/usecase/mock/search_recipes_usecase_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/seka/reci-pin/backend/internal/domain/model"
	recipe "github.com/seka/reci-pin/backend/internal/usecase/recipe"
	gomock "go.uber.org/mock/gomock"
)

// MockSearchRecipesUseCase is a mock of SearchRecipesUseCase interface.
type MockSearchRecipesUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockSearchRecipesUseCaseMockRecorder
	isgomock struct{}
}

// MockSearchRecipesUseCaseMockRecorder is the mock recorder for MockSearchRecipesUseCase.
type MockSearchRecipesUseCaseMockRecorder struct {
	mock *MockSearchRecipesUseCase
}

// NewMockSearchRecipesUseCase creates a new mock instance.
func NewMockSearchRecipesUseCase(ctrl *gomock.Controller) *MockSearchRecipesUseCase {
	mock := &MockSearchRecipesUseCase{ctrl: ctrl}
	mock.recorder = &MockSearchRecipesUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchRecipesUseCase) EXPECT() *MockSearchRecipesUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockSearchRecipesUseCase) Execute(ctx context.Context, input recipe.SearchRecipesInput) ([]model.Recipe, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].([]model.Recipe)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockSearchRecipesUseCaseMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockSearchRecipesUseCase)(nil).Execute), ctx, input)
}
