// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/auth/signup_usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/auth/signup_usecase.go -destination=internal/usecase/mock/signup_usecase_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	auth "github.com/seka/reci-pin/backend/internal/usecase/auth"
	gomock "go.uber.org/mock/gomock"
)

// MockSignupUseCase is a mock of SignupUseCase interface.
type MockSignupUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockSignupUseCaseMockRecorder
	isgomock struct{}
}

// MockSignupUseCaseMockRecorder is the mock recorder for MockSignupUseCase.
type MockSignupUseCaseMockRecorder struct {
	mock *MockSignupUseCase
}

// NewMockSignupUseCase creates a new mock instance.
func NewMockSignupUseCase(ctrl *gomock.Controller) *MockSignupUseCase {
	mock := &MockSignupUseCase{ctrl: ctrl}
	mock.recorder = &MockSignupUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSignupUseCase) EXPECT() *MockSignupUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockSignupUseCase) Execute(ctx context.Context, input auth.SignupInput) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockSignupUseCaseMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockSignupUseCase)(nil).Execute), ctx, input)
}
