// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/auth/token_usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/auth/token_usecase.go -destination=internal/usecase/mock/token_usecase_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockValidateTokenUseCase is a mock of ValidateTokenUseCase interface.
type MockValidateTokenUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockValidateTokenUseCaseMockRecorder
	isgomock struct{}
}

// MockValidateTokenUseCaseMockRecorder is the mock recorder for MockValidateTokenUseCase.
type MockValidateTokenUseCaseMockRecorder struct {
	mock *MockValidateTokenUseCase
}

// NewMockValidateTokenUseCase creates a new mock instance.
func NewMockValidateTokenUseCase(ctrl *gomock.Controller) *MockValidateTokenUseCase {
	mock := &MockValidateTokenUseCase{ctrl: ctrl}
	mock.recorder = &MockValidateTokenUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidateTokenUseCase) EXPECT() *MockValidateTokenUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockValidateTokenUseCase) Execute(tokenString string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", tokenString)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockValidateTokenUseCaseMockRecorder) Execute(tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockValidateTokenUseCase)(nil).Execute), tokenString)
}

// MockGenerateTokenUseCase is a mock of GenerateTokenUseCase interface.
type MockGenerateTokenUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGenerateTokenUseCaseMockRecorder
	isgomock struct{}
}

// MockGenerateTokenUseCaseMockRecorder is the mock recorder for MockGenerateTokenUseCase.
type MockGenerateTokenUseCaseMockRecorder struct {
	mock *MockGenerateTokenUseCase
}

// NewMockGenerateTokenUseCase creates a new mock instance.
func NewMockGenerateTokenUseCase(ctrl *gomock.Controller) *MockGenerateTokenUseCase {
	mock := &MockGenerateTokenUseCase{ctrl: ctrl}
	mock.recorder = &MockGenerateTokenUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGenerateTokenUseCase) EXPECT() *MockGenerateTokenUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGenerateTokenUseCase) Execute(userID int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGenerateTokenUseCaseMockRecorder) Execute(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGenerateTokenUseCase)(nil).Execute), userID)
}
