// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/recipe/update_recipe_usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/recipe/update_recipe_usecase.go -destination=internal/usecase/mock/update_recipe_usecase_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/seka/reci-pin/backend/internal/domain/model"
	recipe "github.com/seka/reci-pin/backend/internal/usecase/recipe"
	gomock "go.uber.org/mock/gomock"
)

// MockUpdateRecipeUseCase is a mock of UpdateRecipeUseCase interface.
type MockUpdateRecipeUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateRecipeUseCaseMockRecorder
	isgomock struct{}
}

// MockUpdateRecipeUseCaseMockRecorder is the mock recorder for MockUpdateRecipeUseCase.
type MockUpdateRecipeUseCaseMockRecorder struct {
	mock *MockUpdateRecipeUseCase
}

// NewMockUpdateRecipeUseCase creates a new mock instance.
func NewMockUpdateRecipeUseCase(ctrl *gomock.Controller) *MockUpdateRecipeUseCase {
	mock := &MockUpdateRecipeUseCase{ctrl: ctrl}
	mock.recorder = &MockUpdateRecipeUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateRecipeUseCase) EXPECT() *MockUpdateRecipeUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockUpdateRecipeUseCase) Execute(ctx context.Context, input recipe.UpdateRecipeInput) (*model.Recipe, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(*model.Recipe)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockUpdateRecipeUseCaseMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockUpdateRecipeUseCase)(nil).Execute), ctx, input)
}
