// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/auth/verify_email_usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/auth/verify_email_usecase.go -destination=internal/usecase/mock/verify_email_usecase_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockVerifyEmailUseCase is a mock of VerifyEmailUseCase interface.
type MockVerifyEmailUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockVerifyEmailUseCaseMockRecorder
	isgomock struct{}
}

// MockVerifyEmailUseCaseMockRecorder is the mock recorder for MockVerifyEmailUseCase.
type MockVerifyEmailUseCaseMockRecorder struct {
	mock *MockVerifyEmailUseCase
}

// NewMockVerifyEmailUseCase creates a new mock instance.
func NewMockVerifyEmailUseCase(ctrl *gomock.Controller) *MockVerifyEmailUseCase {
	mock := &MockVerifyEmailUseCase{ctrl: ctrl}
	mock.recorder = &MockVerifyEmailUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVerifyEmailUseCase) EXPECT() *MockVerifyEmailUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockVerifyEmailUseCase) Execute(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockVerifyEmailUseCaseMockRecorder) Execute(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockVerifyEmailUseCase)(nil).Execute), ctx, token)
}
