// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/auth/withdraw_usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/auth/withdraw_usecase.go -destination=internal/usecase/mock/withdraw_usecase_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWithdrawUseCase is a mock of WithdrawUseCase interface.
type MockWithdrawUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockWithdrawUseCaseMockRecorder
	isgomock struct{}
}

// MockWithdrawUseCaseMockRecorder is the mock recorder for MockWithdrawUseCase.
type MockWithdrawUseCaseMockRecorder struct {
	mock *MockWithdrawUseCase
}

// NewMockWithdrawUseCase creates a new mock instance.
func NewMockWithdrawUseCase(ctrl *gomock.Controller) *MockWithdrawUseCase {
	mock := &MockWithdrawUseCase{ctrl: ctrl}
	mock.recorder = &MockWithdrawUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWithdrawUseCase) EXPECT() *MockWithdrawUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockWithdrawUseCase) Execute(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockWithdrawUseCaseMockRecorder) Execute(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockWithdrawUseCase)(nil).Execute), ctx, userID)
}
