// Code generated by MockGen. DO NOT EDIT.
// Source: recipe_image_repository.go
//
// Generated by this command:
//
//	mockgen -source=recipe_image_repository.go -destination=./mock/recipe_image_repository_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/seka/reci-pin/backend/internal/domain/model"
	gomock "go.uber.org/mock/gomock"
)

// MockRecipeImageRepository is a mock of RecipeImageRepository interface.
type MockRecipeImageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRecipeImageRepositoryMockRecorder
	isgomock struct{}
}

// MockRecipeImageRepositoryMockRecorder is the mock recorder for MockRecipeImageRepository.
type MockRecipeImageRepositoryMockRecorder struct {
	mock *MockRecipeImageRepository
}

// NewMockRecipeImageRepository creates a new mock instance.
func NewMockRecipeImageRepository(ctrl *gomock.Controller) *MockRecipeImageRepository {
	mock := &MockRecipeImageRepository{ctrl: ctrl}
	mock.recorder = &MockRecipeImageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecipeImageRepository) EXPECT() *MockRecipeImageRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRecipeImageRepository) Create(ctx context.Context, image *model.RecipeImage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, image)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRecipeImageRepositoryMockRecorder) Create(ctx, image any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRecipeImageRepository)(nil).Create), ctx, image)
}

// Delete mocks base method.
func (m *MockRecipeImageRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRecipeImageRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRecipeImageRepository)(nil).Delete), ctx, id)
}

// GetByRecipeID mocks base method.
func (m *MockRecipeImageRepository) GetByRecipeID(ctx context.Context, recipeID int64) ([]model.RecipeImage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByRecipeID", ctx, recipeID)
	ret0, _ := ret[0].([]model.RecipeImage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByRecipeID indicates an expected call of GetByRecipeID.
func (mr *MockRecipeImageRepositoryMockRecorder) GetByRecipeID(ctx, recipeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByRecipeID", reflect.TypeOf((*MockRecipeImageRepository)(nil).GetByRecipeID), ctx, recipeID)
}

// GetByRecipeIDs mocks base method.
func (m *MockRecipeImageRepository) GetByRecipeIDs(ctx context.Context, recipeIDs []int64) (map[int64][]model.RecipeImage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByRecipeIDs", ctx, recipeIDs)
	ret0, _ := ret[0].(map[int64][]model.RecipeImage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByRecipeIDs indicates an expected call of GetByRecipeIDs.
func (mr *MockRecipeImageRepositoryMockRecorder) GetByRecipeIDs(ctx, recipeIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByRecipeIDs", reflect.TypeOf((*MockRecipeImageRepository)(nil).GetByRecipeIDs), ctx, recipeIDs)
}
