// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/recipe_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/recipe_repository.go -destination=internal/domain/repository/mock/recipe_repository_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/seka/reci-pin/backend/internal/domain/model"
	gomock "go.uber.org/mock/gomock"
)

// MockRecipeRepository is a mock of RecipeRepository interface.
type MockRecipeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRecipeRepositoryMockRecorder
	isgomock struct{}
}

// MockRecipeRepositoryMockRecorder is the mock recorder for MockRecipeRepository.
type MockRecipeRepositoryMockRecorder struct {
	mock *MockRecipeRepository
}

// NewMockRecipeRepository creates a new mock instance.
func NewMockRecipeRepository(ctrl *gomock.Controller) *MockRecipeRepository {
	mock := &MockRecipeRepository{ctrl: ctrl}
	mock.recorder = &MockRecipeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecipeRepository) EXPECT() *MockRecipeRepositoryMockRecorder {
	return m.recorder
}

// AddTags mocks base method.
func (m *MockRecipeRepository) AddTags(ctx context.Context, recipeID int64, tagIDs []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTags", ctx, recipeID, tagIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTags indicates an expected call of AddTags.
func (mr *MockRecipeRepositoryMockRecorder) AddTags(ctx, recipeID, tagIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTags", reflect.TypeOf((*MockRecipeRepository)(nil).AddTags), ctx, recipeID, tagIDs)
}

// Create mocks base method.
func (m *MockRecipeRepository) Create(ctx context.Context, recipe *model.Recipe) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, recipe)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRecipeRepositoryMockRecorder) Create(ctx, recipe any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRecipeRepository)(nil).Create), ctx, recipe)
}

// Delete mocks base method.
func (m *MockRecipeRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRecipeRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRecipeRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockRecipeRepository) GetByID(ctx context.Context, id int64) (*model.Recipe, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Recipe)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRecipeRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRecipeRepository)(nil).GetByID), ctx, id)
}

// GetByUserID mocks base method.
func (m *MockRecipeRepository) GetByUserID(ctx context.Context, userID int64) ([]model.Recipe, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].([]model.Recipe)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockRecipeRepositoryMockRecorder) GetByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockRecipeRepository)(nil).GetByUserID), ctx, userID)
}

// GetTags mocks base method.
func (m *MockRecipeRepository) GetTags(ctx context.Context, recipeID int64) ([]model.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTags", ctx, recipeID)
	ret0, _ := ret[0].([]model.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTags indicates an expected call of GetTags.
func (mr *MockRecipeRepositoryMockRecorder) GetTags(ctx, recipeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTags", reflect.TypeOf((*MockRecipeRepository)(nil).GetTags), ctx, recipeID)
}

// RemoveTags mocks base method.
func (m *MockRecipeRepository) RemoveTags(ctx context.Context, recipeID int64, tagIDs []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTags", ctx, recipeID, tagIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveTags indicates an expected call of RemoveTags.
func (mr *MockRecipeRepositoryMockRecorder) RemoveTags(ctx, recipeID, tagIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTags", reflect.TypeOf((*MockRecipeRepository)(nil).RemoveTags), ctx, recipeID, tagIDs)
}

// Search mocks base method.
func (m *MockRecipeRepository) Search(ctx context.Context, userID int64, query string, tagIDs []int64) ([]model.Recipe, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, userID, query, tagIDs)
	ret0, _ := ret[0].([]model.Recipe)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockRecipeRepositoryMockRecorder) Search(ctx, userID, query, tagIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockRecipeRepository)(nil).Search), ctx, userID, query, tagIDs)
}

// Update mocks base method.
func (m *MockRecipeRepository) Update(ctx context.Context, recipe *model.Recipe) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, recipe)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRecipeRepositoryMockRecorder) Update(ctx, recipe any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRecipeRepository)(nil).Update), ctx, recipe)
}
