// Code generated by MockGen. DO NOT EDIT.
// Source: search_repository.go
//
// Generated by this command:
//
//	mockgen -source=search_repository.go -destination=./mock/search_repository_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/seka/reci-pin/backend/internal/domain/model"
	repository "github.com/seka/reci-pin/backend/internal/domain/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockRecipeSearchRepository is a mock of RecipeSearchRepository interface.
type MockRecipeSearchRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRecipeSearchRepositoryMockRecorder
	isgomock struct{}
}

// MockRecipeSearchRepositoryMockRecorder is the mock recorder for MockRecipeSearchRepository.
type MockRecipeSearchRepositoryMockRecorder struct {
	mock *MockRecipeSearchRepository
}

// NewMockRecipeSearchRepository creates a new mock instance.
func NewMockRecipeSearchRepository(ctrl *gomock.Controller) *MockRecipeSearchRepository {
	mock := &MockRecipeSearchRepository{ctrl: ctrl}
	mock.recorder = &MockRecipeSearchRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecipeSearchRepository) EXPECT() *MockRecipeSearchRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockRecipeSearchRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRecipeSearchRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRecipeSearchRepository)(nil).Delete), ctx, id)
}

// Index mocks base method.
func (m *MockRecipeSearchRepository) Index(ctx context.Context, recipe *model.Recipe) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Index", ctx, recipe)
	ret0, _ := ret[0].(error)
	return ret0
}

// Index indicates an expected call of Index.
func (mr *MockRecipeSearchRepositoryMockRecorder) Index(ctx, recipe any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Index", reflect.TypeOf((*MockRecipeSearchRepository)(nil).Index), ctx, recipe)
}

// Search mocks base method.
func (m *MockRecipeSearchRepository) Search(ctx context.Context, criteria repository.SearchCriteria) ([]int64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, criteria)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Search indicates an expected call of Search.
func (mr *MockRecipeSearchRepositoryMockRecorder) Search(ctx, criteria any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockRecipeSearchRepository)(nil).Search), ctx, criteria)
}
