// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/user_email_credential_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/user_email_credential_repository.go -destination=internal/domain/repository/mock/user_email_credential_repository_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/seka/reci-pin/backend/internal/domain/model"
	gomock "go.uber.org/mock/gomock"
)

// MockUserEmailCredentialRepository is a mock of UserEmailCredentialRepository interface.
type MockUserEmailCredentialRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserEmailCredentialRepositoryMockRecorder
	isgomock struct{}
}

// MockUserEmailCredentialRepositoryMockRecorder is the mock recorder for MockUserEmailCredentialRepository.
type MockUserEmailCredentialRepositoryMockRecorder struct {
	mock *MockUserEmailCredentialRepository
}

// NewMockUserEmailCredentialRepository creates a new mock instance.
func NewMockUserEmailCredentialRepository(ctrl *gomock.Controller) *MockUserEmailCredentialRepository {
	mock := &MockUserEmailCredentialRepository{ctrl: ctrl}
	mock.recorder = &MockUserEmailCredentialRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserEmailCredentialRepository) EXPECT() *MockUserEmailCredentialRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserEmailCredentialRepository) Create(ctx context.Context, credential *model.UserEmailCredential) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, credential)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserEmailCredentialRepositoryMockRecorder) Create(ctx, credential any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserEmailCredentialRepository)(nil).Create), ctx, credential)
}

// GetByEmail mocks base method.
func (m *MockUserEmailCredentialRepository) GetByEmail(ctx context.Context, email string) (*model.UserEmailCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(*model.UserEmailCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserEmailCredentialRepositoryMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserEmailCredentialRepository)(nil).GetByEmail), ctx, email)
}

// GetByToken mocks base method.
func (m *MockUserEmailCredentialRepository) GetByToken(ctx context.Context, token string) (*model.UserEmailCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByToken", ctx, token)
	ret0, _ := ret[0].(*model.UserEmailCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByToken indicates an expected call of GetByToken.
func (mr *MockUserEmailCredentialRepositoryMockRecorder) GetByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByToken", reflect.TypeOf((*MockUserEmailCredentialRepository)(nil).GetByToken), ctx, token)
}

// GetByUserID mocks base method.
func (m *MockUserEmailCredentialRepository) GetByUserID(ctx context.Context, userID int64) (*model.UserEmailCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].(*model.UserEmailCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockUserEmailCredentialRepositoryMockRecorder) GetByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockUserEmailCredentialRepository)(nil).GetByUserID), ctx, userID)
}

// Update mocks base method.
func (m *MockUserEmailCredentialRepository) Update(ctx context.Context, credential *model.UserEmailCredential) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, credential)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserEmailCredentialRepositoryMockRecorder) Update(ctx, credential any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserEmailCredentialRepository)(nil).Update), ctx, credential)
}

// UpdatePassword mocks base method.
func (m *MockUserEmailCredentialRepository) UpdatePassword(ctx context.Context, userID int64, passwordHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", ctx, userID, passwordHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockUserEmailCredentialRepositoryMockRecorder) UpdatePassword(ctx, userID, passwordHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockUserEmailCredentialRepository)(nil).UpdatePassword), ctx, userID, passwordHash)
}
