// Code generated by MockGen. DO NOT EDIT.
// Source: internal/infrastructure/email/email_sender.go
//
// Generated by this command:
//
//	mockgen -source=internal/infrastructure/email/email_sender.go -destination=internal/infrastructure/email/mock/email_sender_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEmailSender is a mock of EmailSender interface.
type MockEmailSender struct {
	ctrl     *gomock.Controller
	recorder *MockEmailSenderMockRecorder
	isgomock struct{}
}

// MockEmailSenderMockRecorder is the mock recorder for MockEmailSender.
type MockEmailSenderMockRecorder struct {
	mock *MockEmailSender
}

// NewMockEmailSender creates a new mock instance.
func NewMockEmailSender(ctrl *gomock.Controller) *MockEmailSender {
	mock := &MockEmailSender{ctrl: ctrl}
	mock.recorder = &MockEmailSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailSender) EXPECT() *MockEmailSenderMockRecorder {
	return m.recorder
}

// SendPasswordChangeNotification mocks base method.
func (m *MockEmailSender) SendPasswordChangeNotification(to string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendPasswordChangeNotification", to)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendPasswordChangeNotification indicates an expected call of SendPasswordChangeNotification.
func (mr *MockEmailSenderMockRecorder) SendPasswordChangeNotification(to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPasswordChangeNotification", reflect.TypeOf((*MockEmailSender)(nil).SendPasswordChangeNotification), to)
}
