// Code generated by MockGen. DO NOT EDIT.
// Source: usecase_registry.go
//
// Generated by this command:
//
//	mockgen -source=usecase_registry.go -destination=mock/usecase_registry_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	auth "github.com/seka/reci-pin/backend/internal/usecase/auth"
	recipe "github.com/seka/reci-pin/backend/internal/usecase/recipe"
	recipe_image "github.com/seka/reci-pin/backend/internal/usecase/recipe_image"
	recipe_tag "github.com/seka/reci-pin/backend/internal/usecase/recipe_tag"
	tag "github.com/seka/reci-pin/backend/internal/usecase/tag"
	gomock "go.uber.org/mock/gomock"
)

// MockUseCase is a mock of UseCase interface.
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
	isgomock struct{}
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase.
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance.
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// NewAddTagsUseCase mocks base method.
func (m *MockUseCase) NewAddTagsUseCase() recipe_tag.AddTagsUseCase {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewAddTagsUseCase")
	ret0, _ := ret[0].(recipe_tag.AddTagsUseCase)
	return ret0
}

// NewAddTagsUseCase indicates an expected call of NewAddTagsUseCase.
func (mr *MockUseCaseMockRecorder) NewAddTagsUseCase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewAddTagsUseCase", reflect.TypeOf((*MockUseCase)(nil).NewAddTagsUseCase))
}

// NewChangePasswordUseCase mocks base method.
func (m *MockUseCase) NewChangePasswordUseCase() auth.ChangePasswordUseCase {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewChangePasswordUseCase")
	ret0, _ := ret[0].(auth.ChangePasswordUseCase)
	return ret0
}

// NewChangePasswordUseCase indicates an expected call of NewChangePasswordUseCase.
func (mr *MockUseCaseMockRecorder) NewChangePasswordUseCase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewChangePasswordUseCase", reflect.TypeOf((*MockUseCase)(nil).NewChangePasswordUseCase))
}

// NewCreateRecipeImageUseCase mocks base method.
func (m *MockUseCase) NewCreateRecipeImageUseCase() recipe_image.CreateRecipeImageUseCase {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewCreateRecipeImageUseCase")
	ret0, _ := ret[0].(recipe_image.CreateRecipeImageUseCase)
	return ret0
}

// NewCreateRecipeImageUseCase indicates an expected call of NewCreateRecipeImageUseCase.
func (mr *MockUseCaseMockRecorder) NewCreateRecipeImageUseCase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewCreateRecipeImageUseCase", reflect.TypeOf((*MockUseCase)(nil).NewCreateRecipeImageUseCase))
}

// NewCreateRecipeUseCase mocks base method.
func (m *MockUseCase) NewCreateRecipeUseCase() recipe.CreateRecipeUseCase {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewCreateRecipeUseCase")
	ret0, _ := ret[0].(recipe.CreateRecipeUseCase)
	return ret0
}

// NewCreateRecipeUseCase indicates an expected call of NewCreateRecipeUseCase.
func (mr *MockUseCaseMockRecorder) NewCreateRecipeUseCase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewCreateRecipeUseCase", reflect.TypeOf((*MockUseCase)(nil).NewCreateRecipeUseCase))
}

// NewCreateTagUseCase mocks base method.
func (m *MockUseCase) NewCreateTagUseCase() tag.CreateTagUseCase {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewCreateTagUseCase")
	ret0, _ := ret[0].(tag.CreateTagUseCase)
	return ret0
}

// NewCreateTagUseCase indicates an expected call of NewCreateTagUseCase.
func (mr *MockUseCaseMockRecorder) NewCreateTagUseCase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewCreateTagUseCase", reflect.TypeOf((*MockUseCase)(nil).NewCreateTagUseCase))
}

// NewDeleteRecipeUseCase mocks base method.
func (m *MockUseCase) NewDeleteRecipeUseCase() recipe.DeleteRecipeUseCase {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewDeleteRecipeUseCase")
	ret0, _ := ret[0].(recipe.DeleteRecipeUseCase)
	return ret0
}

// NewDeleteRecipeUseCase indicates an expected call of NewDeleteRecipeUseCase.
func (mr *MockUseCaseMockRecorder) NewDeleteRecipeUseCase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewDeleteRecipeUseCase", reflect.TypeOf((*MockUseCase)(nil).NewDeleteRecipeUseCase))
}

// NewDeleteTagUseCase mocks base method.
func (m *MockUseCase) NewDeleteTagUseCase() tag.DeleteTagUseCase {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewDeleteTagUseCase")
	ret0, _ := ret[0].(tag.DeleteTagUseCase)
	return ret0
}

// NewDeleteTagUseCase indicates an expected call of NewDeleteTagUseCase.
func (mr *MockUseCaseMockRecorder) NewDeleteTagUseCase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewDeleteTagUseCase", reflect.TypeOf((*MockUseCase)(nil).NewDeleteTagUseCase))
}

// NewGenerateTokenUseCase mocks base method.
func (m *MockUseCase) NewGenerateTokenUseCase() auth.GenerateTokenUseCase {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewGenerateTokenUseCase")
	ret0, _ := ret[0].(auth.GenerateTokenUseCase)
	return ret0
}

// NewGenerateTokenUseCase indicates an expected call of NewGenerateTokenUseCase.
func (mr *MockUseCaseMockRecorder) NewGenerateTokenUseCase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewGenerateTokenUseCase", reflect.TypeOf((*MockUseCase)(nil).NewGenerateTokenUseCase))
}

// NewGetAllTagsUseCase mocks base method.
func (m *MockUseCase) NewGetAllTagsUseCase() tag.GetAllTagsUseCase {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewGetAllTagsUseCase")
	ret0, _ := ret[0].(tag.GetAllTagsUseCase)
	return ret0
}

// NewGetAllTagsUseCase indicates an expected call of NewGetAllTagsUseCase.
func (mr *MockUseCaseMockRecorder) NewGetAllTagsUseCase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewGetAllTagsUseCase", reflect.TypeOf((*MockUseCase)(nil).NewGetAllTagsUseCase))
}

// NewGetRecipeUseCase mocks base method.
func (m *MockUseCase) NewGetRecipeUseCase() recipe.GetRecipeUseCase {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewGetRecipeUseCase")
	ret0, _ := ret[0].(recipe.GetRecipeUseCase)
	return ret0
}

// NewGetRecipeUseCase indicates an expected call of NewGetRecipeUseCase.
func (mr *MockUseCaseMockRecorder) NewGetRecipeUseCase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewGetRecipeUseCase", reflect.TypeOf((*MockUseCase)(nil).NewGetRecipeUseCase))
}

// NewGetUserRecipesUseCase mocks base method.
func (m *MockUseCase) NewGetUserRecipesUseCase() recipe.GetUserRecipesUseCase {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewGetUserRecipesUseCase")
	ret0, _ := ret[0].(recipe.GetUserRecipesUseCase)
	return ret0
}

// NewGetUserRecipesUseCase indicates an expected call of NewGetUserRecipesUseCase.
func (mr *MockUseCaseMockRecorder) NewGetUserRecipesUseCase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewGetUserRecipesUseCase", reflect.TypeOf((*MockUseCase)(nil).NewGetUserRecipesUseCase))
}

// NewGetUserUseCase mocks base method.
func (m *MockUseCase) NewGetUserUseCase() auth.GetUserUseCase {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewGetUserUseCase")
	ret0, _ := ret[0].(auth.GetUserUseCase)
	return ret0
}

// NewGetUserUseCase indicates an expected call of NewGetUserUseCase.
func (mr *MockUseCaseMockRecorder) NewGetUserUseCase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewGetUserUseCase", reflect.TypeOf((*MockUseCase)(nil).NewGetUserUseCase))
}

// NewLoginUseCase mocks base method.
func (m *MockUseCase) NewLoginUseCase() auth.LoginUseCase {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewLoginUseCase")
	ret0, _ := ret[0].(auth.LoginUseCase)
	return ret0
}

// NewLoginUseCase indicates an expected call of NewLoginUseCase.
func (mr *MockUseCaseMockRecorder) NewLoginUseCase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewLoginUseCase", reflect.TypeOf((*MockUseCase)(nil).NewLoginUseCase))
}

// NewLogoutUseCase mocks base method.
func (m *MockUseCase) NewLogoutUseCase() auth.LogoutUseCase {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewLogoutUseCase")
	ret0, _ := ret[0].(auth.LogoutUseCase)
	return ret0
}

// NewLogoutUseCase indicates an expected call of NewLogoutUseCase.
func (mr *MockUseCaseMockRecorder) NewLogoutUseCase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewLogoutUseCase", reflect.TypeOf((*MockUseCase)(nil).NewLogoutUseCase))
}

// NewRefreshTokenUseCase mocks base method.
func (m *MockUseCase) NewRefreshTokenUseCase() auth.RefreshTokenUseCase {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewRefreshTokenUseCase")
	ret0, _ := ret[0].(auth.RefreshTokenUseCase)
	return ret0
}

// NewRefreshTokenUseCase indicates an expected call of NewRefreshTokenUseCase.
func (mr *MockUseCaseMockRecorder) NewRefreshTokenUseCase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewRefreshTokenUseCase", reflect.TypeOf((*MockUseCase)(nil).NewRefreshTokenUseCase))
}

// NewRemoveTagsUseCase mocks base method.
func (m *MockUseCase) NewRemoveTagsUseCase() recipe_tag.RemoveTagsUseCase {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewRemoveTagsUseCase")
	ret0, _ := ret[0].(recipe_tag.RemoveTagsUseCase)
	return ret0
}

// NewRemoveTagsUseCase indicates an expected call of NewRemoveTagsUseCase.
func (mr *MockUseCaseMockRecorder) NewRemoveTagsUseCase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewRemoveTagsUseCase", reflect.TypeOf((*MockUseCase)(nil).NewRemoveTagsUseCase))
}

// NewRequestPasswordResetUseCase mocks base method.
func (m *MockUseCase) NewRequestPasswordResetUseCase() auth.RequestPasswordResetUseCase {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewRequestPasswordResetUseCase")
	ret0, _ := ret[0].(auth.RequestPasswordResetUseCase)
	return ret0
}

// NewRequestPasswordResetUseCase indicates an expected call of NewRequestPasswordResetUseCase.
func (mr *MockUseCaseMockRecorder) NewRequestPasswordResetUseCase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewRequestPasswordResetUseCase", reflect.TypeOf((*MockUseCase)(nil).NewRequestPasswordResetUseCase))
}

// NewResetPasswordUseCase mocks base method.
func (m *MockUseCase) NewResetPasswordUseCase() auth.ResetPasswordUseCase {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewResetPasswordUseCase")
	ret0, _ := ret[0].(auth.ResetPasswordUseCase)
	return ret0
}

// NewResetPasswordUseCase indicates an expected call of NewResetPasswordUseCase.
func (mr *MockUseCaseMockRecorder) NewResetPasswordUseCase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewResetPasswordUseCase", reflect.TypeOf((*MockUseCase)(nil).NewResetPasswordUseCase))
}

// NewSearchRecipesUseCase mocks base method.
func (m *MockUseCase) NewSearchRecipesUseCase() recipe.SearchRecipesUseCase {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewSearchRecipesUseCase")
	ret0, _ := ret[0].(recipe.SearchRecipesUseCase)
	return ret0
}

// NewSearchRecipesUseCase indicates an expected call of NewSearchRecipesUseCase.
func (mr *MockUseCaseMockRecorder) NewSearchRecipesUseCase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewSearchRecipesUseCase", reflect.TypeOf((*MockUseCase)(nil).NewSearchRecipesUseCase))
}

// NewSignupUseCase mocks base method.
func (m *MockUseCase) NewSignupUseCase() auth.SignupUseCase {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewSignupUseCase")
	ret0, _ := ret[0].(auth.SignupUseCase)
	return ret0
}

// NewSignupUseCase indicates an expected call of NewSignupUseCase.
func (mr *MockUseCaseMockRecorder) NewSignupUseCase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewSignupUseCase", reflect.TypeOf((*MockUseCase)(nil).NewSignupUseCase))
}

// NewUpdateRecipeUseCase mocks base method.
func (m *MockUseCase) NewUpdateRecipeUseCase() recipe.UpdateRecipeUseCase {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewUpdateRecipeUseCase")
	ret0, _ := ret[0].(recipe.UpdateRecipeUseCase)
	return ret0
}

// NewUpdateRecipeUseCase indicates an expected call of NewUpdateRecipeUseCase.
func (mr *MockUseCaseMockRecorder) NewUpdateRecipeUseCase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewUpdateRecipeUseCase", reflect.TypeOf((*MockUseCase)(nil).NewUpdateRecipeUseCase))
}

// NewValidateTokenUseCase mocks base method.
func (m *MockUseCase) NewValidateTokenUseCase() auth.ValidateTokenUseCase {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewValidateTokenUseCase")
	ret0, _ := ret[0].(auth.ValidateTokenUseCase)
	return ret0
}

// NewValidateTokenUseCase indicates an expected call of NewValidateTokenUseCase.
func (mr *MockUseCaseMockRecorder) NewValidateTokenUseCase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewValidateTokenUseCase", reflect.TypeOf((*MockUseCase)(nil).NewValidateTokenUseCase))
}

// NewVerifyEmailUseCase mocks base method.
func (m *MockUseCase) NewVerifyEmailUseCase() auth.VerifyEmailUseCase {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewVerifyEmailUseCase")
	ret0, _ := ret[0].(auth.VerifyEmailUseCase)
	return ret0
}

// NewVerifyEmailUseCase indicates an expected call of NewVerifyEmailUseCase.
func (mr *MockUseCaseMockRecorder) NewVerifyEmailUseCase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewVerifyEmailUseCase", reflect.TypeOf((*MockUseCase)(nil).NewVerifyEmailUseCase))
}

// NewWithdrawUseCase mocks base method.
func (m *MockUseCase) NewWithdrawUseCase() auth.WithdrawUseCase {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewWithdrawUseCase")
	ret0, _ := ret[0].(auth.WithdrawUseCase)
	return ret0
}

// NewWithdrawUseCase indicates an expected call of NewWithdrawUseCase.
func (mr *MockUseCaseMockRecorder) NewWithdrawUseCase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewWithdrawUseCase", reflect.TypeOf((*MockUseCase)(nil).NewWithdrawUseCase))
}
