// Code generated by MockGen. DO NOT EDIT.
// Source: recipe_searcher.go
//
// Generated by this command:
//
//	mockgen -source=recipe_searcher.go -destination=./mock/recipe_searcher_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/seka/reci-pin/backend/internal/domain/model"
	gomock "go.uber.org/mock/gomock"
)

// MockRecipeSearcher is a mock of RecipeSearcher interface.
type MockRecipeSearcher struct {
	ctrl     *gomock.Controller
	recorder *MockRecipeSearcherMockRecorder
	isgomock struct{}
}

// MockRecipeSearcherMockRecorder is the mock recorder for MockRecipeSearcher.
type MockRecipeSearcherMockRecorder struct {
	mock *MockRecipeSearcher
}

// NewMockRecipeSearcher creates a new mock instance.
func NewMockRecipeSearcher(ctrl *gomock.Controller) *MockRecipeSearcher {
	mock := &MockRecipeSearcher{ctrl: ctrl}
	mock.recorder = &MockRecipeSearcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecipeSearcher) EXPECT() *MockRecipeSearcherMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockRecipeSearcher) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRecipeSearcherMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRecipeSearcher)(nil).Delete), ctx, id)
}

// Index mocks base method.
func (m *MockRecipeSearcher) Index(ctx context.Context, recipe *model.Recipe) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Index", ctx, recipe)
	ret0, _ := ret[0].(error)
	return ret0
}

// Index indicates an expected call of Index.
func (mr *MockRecipeSearcherMockRecorder) Index(ctx, recipe any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Index", reflect.TypeOf((*MockRecipeSearcher)(nil).Index), ctx, recipe)
}

// Search mocks base method.
func (m *MockRecipeSearcher) Search(ctx context.Context, criteria model.RecipeSearchCriteria) ([]int64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, criteria)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Search indicates an expected call of Search.
func (mr *MockRecipeSearcherMockRecorder) Search(ctx, criteria any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockRecipeSearcher)(nil).Search), ctx, criteria)
}
